import { motion } from "framer-motion";
import {
  Accordion,
  AccordionContent,
  AccordionItem,
  AccordionTrigger,
} from "@/components/ui/accordion";

const faqs = [
  {
    question: "How does the AI Blog Writer work?",
    answer: "Our AI Blog Writer uses advanced natural language processing to understand your topic and generate high-quality, SEO-optimized content. Simply enter your topic, customize your preferences, and get a complete blog post in under 60 seconds."
  },
  {
    question: "Is the content original and plagiarism-free?",
    answer: "Yes, all content generated by our AI is 100% original and plagiarism-free. Our advanced algorithms create unique content based on your specifications, and we include built-in plagiarism checking to ensure originality."
  },
  {
    question: "Can I edit the generated content?",
    answer: "Absolutely! Our built-in editor allows you to modify, refine, and personalize the generated content. You can adjust tone, add your own insights, and make any changes needed to match your brand voice."
  },
  {
    question: "What languages are supported?",
    answer: "We support over 25 languages including English, Spanish, French, German, Italian, Portuguese, Dutch, and many more. You can generate content in your preferred language with the same quality and SEO optimization."
  },
  {
    question: "How much does it cost?",
    answer: "We offer flexible pricing plans starting with a free tier that includes 2,000 words per month. Our paid plans start at $19/month for unlimited content generation, advanced features, and priority support."
  },
  {
    question: "Is there a free trial?",
    answer: "Yes! You can start with our free plan that includes 2,000 words per month. No credit card required. Upgrade anytime to access unlimited content generation and premium features."
  }
];

export const FAQ = () => {
  return (
    <section className="py-20 bg-white">
      <div className="container mx-auto px-4">
        <motion.div
          initial={{ opacity: 0, y: 30 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
          className="text-center mb-16"
        >
          <h2 className="text-4xl font-bold text-gray-900 mb-4">
            Frequently Asked Questions
          </h2>
          <p className="text-xl text-gray-600 max-w-3xl mx-auto">
            Everything you need to know about our AI Blog Writer
          </p>
        </motion.div>

        <motion.div
          initial={{ opacity: 0, y: 30 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
          className="max-w-3xl mx-auto"
        >
          <Accordion type="single" collapsible className="space-y-4">
            {faqs.map((faq, index) => (
              <AccordionItem 
                key={index} 
                value={`item-${index}`}
                className="bg-gray-50 rounded-lg px-6 border-0"
              >
                <AccordionTrigger className="text-left font-semibold text-gray-900 hover:no-underline py-6">
                  {faq.question}
                </AccordionTrigger>
                <AccordionContent className="text-gray-600 leading-relaxed pb-6">
                  {faq.answer}
                </AccordionContent>
              </AccordionItem>
            ))}
          </Accordion>
        </motion.div>

        {/* Final CTA */}
        <motion.div
          initial={{ opacity: 0, y: 30 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
          className="text-center mt-16"
        >
          <div className="bg-gradient-to-r from-blue-600 to-purple-700 rounded-2xl p-12 text-white">
            <h3 className="text-3xl font-bold mb-4">
              Make Super-Engaging Blogs with GrammarWrite
            </h3>
            <p className="text-xl mb-8 text-blue-100">
              Join over 50,000 content creators and marketers who trust our AI Blog Writer
            </p>
            <button className="bg-white text-blue-600 px-8 py-4 rounded-lg font-semibold text-lg hover:bg-blue-50 transition-colors">
              Get Started Free
            </button>
          </div>
        </motion.div>
      </div>
    </section>
  );
};