name: CD Pipeline

on:
    workflow_run:
      workflows: ["CI Pipeline"]
      types:
        - completed

jobs:

  build:

    runs-on: self-hosted

    # steps:
    # - name: Pull Docker Image
    #   run: sudo docker pull zedmate/inscribeai-ci-pipeline:latest

    # - name: Delete old Docker Container
    #   run: sudo docker rm -f inscribeai-ci-pipeline-container || true

    # - name: Run Docker Container
    #   run: sudo docker run -d -p 80:80 --name inscribeai-ci-pipeline-container zedmate/inscribeai-ci-pipeline
