name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Login Dockerhub
      uses: docker/login-action@v3
      with:
        username: "zedmate"
        password: "dckr_pat_D9kMoCbWtUtGY0p0W0giRkfNZq8"
    - name: Build the Docker image
      run: docker build -t zedmate/inscribeai-ci-pipeline:latest .
    - name: Push to Dockerhub
      run: docker push zedmate/inscribeai-ci-pipeline:latest
