name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Login Dockehub
      env:
        DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: docker login -u $DOCKER_USERNAME --password-stdin $DOCKER_PASSWORD
    - name: Build the Docker image
      run: docker build -t inscribeai-ci-pipeline .
    - name: Push to Dockerhub
      run: docker push zedmate/inscribeai-ci-pipeline:latest
