name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Login Dockerhub
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: echo "bentensmall" | docker login docker.pkg.github.com -u "Zedmate" --password-stdin
    - name: Build the Docker image
      run: docker build -t inscribeai-ci-pipeline:latest .
    - name: Push to Dockerhub
      run: docker push zedmate/inscribeai-ci-pipeline:latest
