name: Call URL every hour

on:
  schedule:
    # Run the action every hour
    - cron: '0 * * * *'  # This cron syntax means "at minute 0 of every hour"

  workflow_dispatch: # This allows you to manually trigger the action

jobs:
  call_url:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository (optional, not always needed unless you're working with the repo)
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Make an HTTP request using curl
      - name: Call the URL
        run: |
          curl -X GET "https://inscribeai.onrender.com/"

